name: mytodo
description: "Flutter project trello"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  oauth1: ^2.0.0
  go_router: ^13.2.0
  provider: ^6.1.2
  webview_flutter: ^4.7.0
  http: ^0.13.6
  google_fonts: ^4.0.4
  mockito: ^5.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Blueberry
      fonts:
        - asset: assets/font-family/Blueberry.ttf
          weight: 400


  assets:
    - assets/font-family/